version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.production
    volumes:
      - ./:/app/
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    # For debugging, you can uncomment the next line to keep the container running without starting the app
    # command: tail -f /dev/null

  db:
    image: postgres:14  # Changed from postgres:15 to postgres:14 which is more widely available
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"  # Expose PostgreSQL to host machine for debugging
    env_file:
      - .env.production
    environment:
      # Additional settings for better development experience
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres_data: